In [ ]:
#Create a NumPy array of integers from 1 to 10

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Create a 2x3 NumPy array filled with zeros.

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Create a NumPy array of even numbers from 2 to 20

In [ ]:
arr=np.arange(2,21,2)

In [ ]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4.Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=arr1+arr2
arr4=arr1-arr2
arr5=arr1*arr2
arr6=arr2/arr1

In [ ]:
arr3

array([5, 7, 9])

In [ ]:
arr4

array([-3, -3, -3])

In [ ]:
arr5

array([ 4, 10, 18])

In [ ]:
arr6

array([4. , 2.5, 2. ])

5.Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [ ]:

import numpy as np
arr = np.random.rand(100)
print(arr)
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

[0.77796517 0.56014606 0.60302257 0.70721228 0.9679547  0.43282696
 0.58162932 0.44201635 0.18006997 0.44644146 0.66299188 0.48630373
 0.35844914 0.17422244 0.71620325 0.43675092 0.82127249 0.40620261
 0.00169134 0.29414815 0.13483147 0.82456305 0.0259332  0.88006263
 0.50588416 0.26457438 0.30857668 0.34619706 0.11353375 0.20853398
 0.12460021 0.31752224 0.10580835 0.80058355 0.43073775 0.05162602
 0.18335861 0.17803462 0.74554235 0.12752625 0.33770299 0.10864462
 0.10054142 0.66439506 0.18168445 0.36035095 0.46703138 0.63930224
 0.68940986 0.39245847 0.37151945 0.26022701 0.50645269 0.03237896
 0.07630321 0.97425918 0.51401755 0.1002333  0.71524557 0.22595947
 0.47001958 0.41489357 0.63816255 0.83457396 0.42077128 0.47947854
 0.13188347 0.88483403 0.54587529 0.28905571 0.5648335  0.75635847
 0.71145914 0.28154424 0.15167059 0.96941897 0.35055422 0.21017259
 0.90902253 0.55888668 0.81001388 0.41805674 0.47237247 0.32368541
 0.7055643  0.83799847 0.96376612 0.62309021 0.52795407 0.9921

6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4)

In [ ]:
arr2=np.random.randint(0,20,12)

In [ ]:
arr2

array([4, 5, 6])

In [ ]:
arr2.reshape(3,4)

array([[ 8,  9, 13,  2],
       [ 0, 18,  8,  6],
       [18,  2,  1,  4]])

7. Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

8. Create a 5x5 identity matrix using NumPy.

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9. Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]).

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [ ]:
arr2=np.arange(0,21)

In [ ]:
arr2.reshape(3,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [ ]:
arr2.max()

In [ ]:
arr2.min()

0

11.Concatenate two random NumPy arrays horizontally and vertically.


In [ ]:
a=np.zeros((3,3))

In [ ]:
b=np.ones((3,3))

In [ ]:
np.vstack([a,b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.hstack([a,b])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.

In [ ]:
arr3=np. array([[1,2,3],[4,5,6]])
print(arr3)
np. sum(arr3,axis=1)

[[1 2 3]
 [4 5 6]]


array([ 6, 15])

In [ ]:
np.sum(arr3,axis=0)

array([5, 7, 9])

13.Find the common elements between two NumPy arrays.

In [ ]:
import numpy as np
array1 =np.array([1, 2, 3, 4, 5])
array2 =np.array([4, 5, 6, 7, 8])
common_elements = np.intersect1d(array1, array2)

print(common_elements)

[4 5]


14.Replace all negative values in a NumPy array with zeros.

In [ ]:
import numpy as np
array = np.array([-1, 2, -3, 4, -5])
array = np.where(array < 0, 0, array)

print(array)

[0 2 0 4 0]


15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.

In [ ]:
import numpy as np
array = np.random.randint(1, 101, size=10)
Print
array.sort()
print(array)

[14 22 24 26 33 46 47 51 73 88]


16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [ ]:

import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
print(array1)
print(array2)
abs_diff = np.abs(array1 - array2)
print(' absolute difference ')
print(abs_diff)

[1 2 3 4 5]
[5 4 3 2 1]
 absolute difference 
[4 2 0 2 4]


17.Given a 2D NumPy array, extract the first row and the last column.

In [ ]:

import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
first_row = arr[0, :]
last_column = arr[:, -1]
print(first_row)
print(last_column)

[1 2 3]
[3 6 9]


18.Slice a 1D NumPy array to get every other element.

In [ ]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
every_other_element = arr[::2]
print(every_other_element)

[1 3 5 7 9]


19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [ ]:

import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7,8]])
row, columns=arr.shape
start_row = row // 2 - 1
end_row = start_row + 2
start_column = columns // 2 - 1
end_column = start_column + 2
subarray = arr[start_row:end_row, start_column:end_column]
print(subarray)

[[2 3]
 [6 7]]


20.Reverse a 1D NumPy array using slicing

In [ ]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
reversed_arr = arr[::-1]
print(reversed_arr)

[1 2 3 4 5]
[5 4 3 2 1]
